# Analysis
### Imports 
#### Run cell to load neccessary packages

In [12]:
import sqlite3
import pandas as pd

### Connect to database

In [13]:
conn = sqlite3.connect("./data/omny.db")

## Questions
### Question 1
What is the average ridership per day

In [15]:
query = """
SELECT day_of_week,avg(est_avg_ridership) as avg_ridership
FROM RIDERSHIP
group by day_of_week
order by avg_ridership desc;
"""

df = pd.read_sql_query(query, conn)

df

  day_of_week  avg_ridership
0      Sunday       1.936752

In [16]:
query = """
SELECT distinct day_of_week
FROM RIDERSHIP;
"""

df = pd.read_sql_query(query, conn)

df

  day_of_week
0      Sunday