# Analysis
### Imports 
#### Run cell to load neccessary packages

In [1]:
import sqlite3
import pandas as pd

### Connect to database

In [2]:
conn = sqlite3.connect("./data/omny.db")

## Questions
### Question 1
What is the average ridership per day

In [3]:
query = """
SELECT day_of_week,avg(est_avg_ridership) as avg_ridership, count(day_of_week) as count
FROM RIDERSHIP
group by day_of_week
order by avg_ridership desc;
"""

df = pd.read_sql_query(query, conn)

df

  day_of_week  avg_ridership  count
0   Wednesday       9.744371  27221
1     Tuesday       9.672668  27007
2    Thursday       9.312340  27542
3      Friday       8.173528  27724
4      Monday       7.907618  27112
5    Saturday       6.299258  27937
6      Sunday       5.032597  27193

In [4]:
query = """
SELECT distinct day_of_week
FROM RIDERSHIP;
"""

df = pd.read_sql_query(query, conn)

df

  day_of_week
0      Friday
1      Monday
2    Saturday
3      Sunday
4    Thursday
5     Tuesday
6   Wednesday

In [6]:
query = """
SELECT distinct year, month
FROM RIDERSHIP;
"""

df = pd.read_sql_query(query, conn)

df

   year  month
0  2026      1
1  2026      2
2  2026      3
3  2026      4
4  2026      5
5  2026      6
6  2026      7
7  2026      8
8  2026      9

In [5]:
query = """
SELECT count(*)
FROM station;
"""

df = pd.read_sql_query(query, conn)

df

   count(*)
0        13